### PR TITLE
2 Simple Fixes

### PR DESCRIPTION
**Pull request by Nitrogen-Dioxide**
These fixes are stupidly simple, but is always good to close an issue.

### CODE REVIEW

**Comment by Alexander01998** [comment]
I could not reproduce #482. It was turned off normally with and without the fix. Tested with the ClickGUI, keybinds and commands.

**Comment by Nitrogen-Dioxide** [comment]
Hmmm this issue is strange, the only way I could reproduce that, was in survival. But by the logic, you must disable sprint before removing the listener.

**Comment by Nitrogen-Dioxide** [comment]
Oh tested again, and it is a very rare issue, sometimes happens, sometimes not, but with the fix, it doesn't happens anymore (for some reason O.o)

**Comment by Alexander01998** [comment]
There once (before v1.14) was a chance that the `UpdateListener` would fire one last time after it had been disabled. Calling `EventManager.update.removeListener(this);` didn't remove the listener directly, but added the task of removing it to a queue.

The new event manager (since v1.14) is able to add/remove listeners directly, so it is likely that v1.14 has fixed this bug.

**Pull request merged**
