### PR TITLE
Autosoup

### PR DESCRIPTION
**Pull request by ThisTestUser**
Since the original author (https://github.com/Ceiridge?tab=activity) hasn't been active, I'll make this pull request here.
The copyright thing is broken again..

### CODE REVIEW

**Comment by ThisTestUser** [comment]
At least say something, so I know that you are aware of this pull request?

**Comment by ThisTestUser** [comment]
Well, I can't fix the encoding because I can't apply minecraft.patch. Can you fix it instead?

**Comment by mcccs** [comment]
You don't need to apply patch to change encoding.
screenshot


Copy this: `ISO-8859-1` And paste it in eclipse

**Comment by Alexander01998** [comment]
Actually, the correct encoding is `Windows 1252`.

**Comment by Alexander01998** [comment]
> However, it doesn't break encoding too.

But it did on [your latest PR](https://github.com/Wurst-Imperium/Wurst-Client/pull/2395).

**Comment by mcccs** [comment]
Because, I used github online for that. 
[That's](https://github.com/Wurst-Imperium/Wurst-Client/pull/2394/files) the PR I used ISO encoding

**Comment by ThisTestUser** [comment]
Well, I'm doing this directly on github, not on eclipse, because I can't apply the patch, which makes it not possible to submit pull requests if the code is erroring...

**Comment by MajesticMagician** [comment]
"Connecting Git team provider failed" how do i fix this?

**Comment by ThisTestUser** [comment]
Make sure you are using the correct software and a proper internet connection.

**Comment by mcccs** [comment]
@ThisTestUser i couldn't too. Give me guide a try.

**Comment by Alexander01998** [comment]
Locking the conversation due to off-topic comments adding clutter.

**Pull request merged**
