### PR TITLE
- Added Villager / Zombie Villager Targeting Options.

### PR DESCRIPTION
**Pull request by mossyblog**
Important feature if you have a Zombie spawner & want to easily kill all Zombies that aren't "Cure-friendly" when they are clustered together. The villager option is useful as well, as in, kill animals / players except villagers in your base.

### CODE REVIEW

**Comment by pokeball99** [comment]
:+1: like it man, should definitely be added

**Comment by Alexander01998** [comment]
Please separate the Target options and the step range.

**Comment by ThisTestUser** [comment]
What about making a "selector" for mobs/monsters, checking which mobs you want to target? And also, if that is to be implanted, a button for targeting "other" mobs would be good for ignoring mobs that are spawned to confuse kill auras. (I've seen this in hypixel UHC, where they spawn "fake" mobs that you target even though invisible mobs is off)

**Comment by pokeball99** [comment]
> [`_****_`](

- 

- [ ] @ #1. url

)

**Comment by mossyblog** [comment]
@Alexander01998 that should resolve the outstanding issues.

Also i've got additional changes for Nuker ID mode. In that it will also enable the user(s) to target variants of the material (ie targeting Logs not just all but Log:Oak, Log:Birch etc.

Is it of any use?

**Comment by mossyblog** [comment]
@ThisTestUser I was mucking around with a Fold-out sub-menu today actually. Idea is you select "monsters" but can then turn down and pick sub options to enable you to be more selective. I was planning on this being attached to Materials as I find NUKER works for harvesting specific mats.

I personally don't use this mod to cause chaos on the server(s) i merely use it as additive behaviours to the grind of Survival ..so for me it's really about helper-mod mode vs kill my neighbours entire farm animals thing.

**Comment by ThisTestUser** [comment]
I would like to be able to select different animals to attack, because sometimes you just want to kill animals but not your wolf. And also there should be a different checkbox for custom mob selection because it should apply to invisible mobs too. 

The thing about Wurst is there is less variability (even though 95% of the clients are like this), like in auto disconnect we are not able to select hearts at disconnect, and that we can't enable the flight bypass and noslowdown (blocked mod) at once.

**Comment by Alexander01998** [comment]
Please sign the CLA.

**Pull request closed without merging**
