### PR TITLE
Better ServerFinder

### PR DESCRIPTION
**Pull request by kim-yannick**
This Pull Request makes the ServerFinder way more efficient. It can find about 6 times more servers (tested using an Nitrado IP). It also adds a cleanup item to remove "Grief Me" servers. This makes it easy to get your old serverlist back without saving it.

serverfinder-new
serverfinder-old
serverfinder-cleanup

### CODE REVIEW

**Comment by kim-yannick** [comment]
Maybe I could also add a DNS resolver, but I am too lazy to implement this right now.

**Comment by mcccs** [comment]
Yes you are right. New remove button might be very useful

**Comment by kim-yannick** [comment]
serverfinder-newer

The newest version features a DNS resolver and a more user friendly GUI. Cancelling is now possible without leaving the GUI. Duplicates are not being added.

**Comment by Alexander01998** [comment]
I have downloaded the PR and will review & merge it later.

**Pull request merged**
