### PR TITLE
AntiPotion

### PR DESCRIPTION
**Pull request by Alexander01998**
Blocks bad potion effects.

### CODE REVIEW

**Comment by OMGchangeMYusername** [comment]
wasn't that already implemented?
if it's different than AntiBlind it's my bad then.

**Comment by Alexander01998** [comment]
AntiBlind blocks blindness, this blocks poison & hunger.

**Comment by OMGchangeMYusername** [comment]
woah is it NCP bypassed?!

**Comment by Alexander01998** [comment]
Nope.

**Pull request merged**
