### PR TITLE
Additional condition to get the message repeated (AnnoyCmd)

### LINKED ISSUE #1415: Annoy feature broken?
u6ug3uv

I annoyed "marco213" in this example but no messages of him were repeated.
Is this feature broken?

### PR DESCRIPTION
**Pull request by GummiBoat**
Simply added a condition, that resolves #1415.

### CODE REVIEW

**Comment by Meylama** [comment]
You added " :", but I would also suggest to add " : " because on the screen of the linked issue, there is also a space after the ":"

**Comment by GummiBoat** [comment]
that doesn't matter, the code splits after the :.

**Comment by Alexander01998** [comment]
See https://github.com/Wurst-Imperium/Wurst-Client/issues/1415#issuecomment-126997474.

**Comment by Bluscream** [comment]
+1 Approve lol, its not a enhancement, its a bugfix, and its worth it. mineplex is not the smallest server in the world.

**Comment by mcccs** [comment]
The biggest server is Pluto-54. But i can't connect. (My Internet connection)

**Comment by Alexander01998** [comment]
> mineplex is not the smallest server in the world.

Mineplex doesn't use this.

**Comment by Meylama** [comment]
Dude it is a BUGFIX, and for you, it is one click and it will automatically fix it, so why you reject it?!

**Pull request closed without merging**
