### PR TITLE
Clean that mess ¯\_(ツ)_/¯

### PR DESCRIPTION
**Pull request by deprilula28**
I just did this on GitHub because I'm lazy, so if I did any sintax mistakes that's why.

### CODE REVIEW

**Comment by mcccs** [comment]
SyntaxError: };

There shouldn't be a semicolon.

**Comment by deprilula28** [comment]
Wait what's wrong with that line

**Comment by pokeball99** [comment]
@Alexander01998 why was this closed?

**Comment by deprilula28** [comment]
No idea..

**Comment by v0idst4r** [comment]
Because you need to lrn2java

**Comment by deprilula28** [comment]
What's that supposed to mean? What is wrong with that line? Is it the import? I guess this is what I get for trying to help a project.

**Comment by v0idst4r** [comment]
It means you need to learn Java. And even if you wanted a CHANCE of this getting merged you should've used a lambada

**Comment by v0idst4r** [comment]
lambda*

**Comment by v0idst4r** [comment]
Here's an example

Arrays.stream(new Mod[] {wurst.mods.killauraMod, wurst.mods.killauraLegitMod, wurst.mods.multiAuraMod, wurst.mods.clickAuraMod, wurst.mods.tpAuraMod}.filter(mod -> mod.isEnabled()).forEach(mod -> mod.isEnabled());

**Comment by v0idst4r** [comment]
Oops. I meant

Arrays.stream(new Mod[] {wurst.mods.killauraMod, wurst.mods.killauraLegitMod, wurst.mods.multiAuraMod, wurst.mods.clickAuraMod, wurst.mods.tpAuraMod}.filter(mod -> mod.isEnabled()).forEach(mod -> mod.setEnabled(false));

**Comment by deprilula28** [comment]
Understood, I can't help a project because then people will judge my Java skills.

**Comment by v0idst4r** [comment]
When you try to contribute horrible code, yes.

**Comment by deprilula28** [comment]
How can I stop getting email notifications off this? Didn't find the option on my settings, and I really don't want to keep getting spammed of people judging my coding skills...

**Comment by supertassu** [comment]
https://puu.sh/qsSHT/bca330ad04.png

**Comment by supertassu** [comment]
@deprilula28  https://puu.sh/qsSHT/bca330ad04.png

**Comment by v0idst4r** [comment]
Kek

**Pull request closed without merging**
