### PR TITLE
Add enchant god for level 32767

### PR DESCRIPTION
**Pull request by ChargedCreeper**
Add .enchant god for level 32767 enchantments.

### CODE REVIEW

**Comment by GummiBoat** [comment]
Your class is completely wrong coded ... did you even tested it?

**Comment by Alexander01998** [comment]
> Your class is completely wrong coded

Looks fine to me, although it's not very efficient.

> did you even tested it?

@ChargedCreeper I'd like to know that too.
The last time I tested it, enchantments above 127 were not possible.

**Comment by GummiBoat** [comment]
> Looks fine to me, although it's not very efficient.
He forgot to add the [all] syntax, he randomly switched between not using curly brackets and using them
```
if() ... else ... }else if{ if() ... else }else ...
```
And I think he duplicated the message that gets sent... (Not really sure on that one tho ^^)

Afaik enchantments can be maximal lvl 32767 (because Mojang changed it to a 16-Bit integer) since ... dunno... a few patches atleast. (/give @p diamond_sword 1 0 {ench:[{id:16,lvl:32767}]}).

**Comment by Alexander01998** [comment]
> He forgot to add the [all] syntax

All there, look at [line 18](https://github.com/Wurst-Imperium/Wurst-Client/pull/755/files#diff-9bcbf032f452d30653a140529015be09R18) & [line 42](https://github.com/Wurst-Imperium/Wurst-Client/pull/755/files#diff-9bcbf032f452d30653a140529015be09R42).

> he randomly switched between not using curly brackets and using them

That isn't random, it's valid Java syntax.

`.enchant god` is a copy of the `.enchant` code with one number changed and the message from `.enchant all` added. It would be better to just change the number in `.enchant` & `.enchant all`.

**Comment by GummiBoat** [comment]
> All there, look at line 18 & line 42.

Sorry for that one, the lines were collapsed. (I didn't saw the little symbol on the left side.)

> That isn't random, it's valid Java syntax.

Yea.. I just don't like it that way. Sorry. (I prefer to close and open everything via curly brackets.)

**Comment by Nitrogen-Dioxide** [comment]
@GummiBoat Sorry to say that, but stop doing this type of criticism :/. @ChargedCreeper Expended time on that. So try to make only constructive criticism please.

Hope you understand what I'm trying to say.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 Other arg can be added, like .enchant ("all or nothing") ("level").

**Comment by GummiBoat** [comment]
> So try to make only constructive criticism please.

Yea. Sorry. I'm a little bored and stupid today.

**Comment by OMGchangeMYusername** [comment]
Disconfirmed .-.

**Pull request closed without merging**
