### PR TITLE
PlayerFinder

### LINKED ISSUE #113: PlayerFinder
u can get coords during thunderstorms
this client has it implemented:
https://github.com/spacerocket/vapid/blob/master/me/pyr0byte/vapid/modules/ModuleSounder.java

### PR DESCRIPTION
**Pull request by Alexander01998**
Finds far players during thunderstorms.

**Needs more tests!**

Resolves #113

### CODE REVIEW

**Comment by pokeball99** [comment]
i whould have thought u were going to make it work for any sound packet,not just lighting

**Comment by Alexander01998** [comment]
> i whould have thought u were going to make it work for any sound packet,not just lighting

So far, my tests have shown that the sound & particle packets can only detect the sounds & particles near lightning strikes.

But like i said, it needs more tests.

**Comment by Alexander01998** [comment]
Tested it on a LAN server and it worked properly.

**Comment by GlitchHead** [comment]
seems cool cant wait to try this.

**Pull request merged**
