### PR TITLE
Annoy for Mineplex and Hypixel

### PR DESCRIPTION
**Pull request by mcccs**
Addition 1:  Mineplex Lobby
Addition 2: Hypixel
Addition 3: Mineplex team games.

### CODE REVIEW

**Comment by ThisTestUser** [comment]
I think you broke the encoding again.

**Comment by wkuba500** [comment]
Just added in ".annoy delay" lel

**Comment by ThisTestUser** [comment]
The annoy delay needs its errors fixed before it can be used.

**Comment by mcccs** [comment]
Nope, encoding is nice.

**Comment by ThisTestUser** [comment]
Your first 2 commits changed the encoding, did they reverse each other?

**Comment by mcccs** [comment]
Yes, I don't know how to create a branch in downloaded Github, so i made the first commit on this website.

**Comment by mcccs** [comment]
@Alexander01998 should I close this one and open the same PR in 1.9 repository?

**Comment by mcccs** [comment]
Moved to: https://github.com/Wurst-Imperium/Wurst-Client-for-MC-1.9.X/pull/1

**Pull request closed without merging**
