### PR TITLE
Manualblink :D

### PR DESCRIPTION
**Pull request by Nitrogen-Dioxide**
It creates a clone of you like free cam to know where you are, (enable blink and drop a item to see what happens) 

Now you can teleport and do a LOT of things. You can even hook items on the ground safely (as I said here) #205 
You can teleport disabling and enabling it, but don't keep it enabled too much time (or too much away from your first position) because it will "real lags" you.

Solves #126 

Please @Alexander01998 add this, is a must have haha .

### CODE REVIEW

**Comment by Alexander01998** [comment]
Merged it into `PR#446-manual-Blink` for testing & editing. I will merge that into `master` when I'm done.

**Comment by TekkitCommando** [comment]
Sounds cool :)

**Comment by WurstLeafeon** [comment]
Does this completely stops and records packets such as dropping items and attacking entities, as well as interacting with blocks?

If not, fix that.

**Comment by Alexander01998** [comment]
> Does this completely stops and records packets such as dropping items and attacking entities, as well as interacting with blocks?

No, Blink only pauses movement packets. Pausing all packets would also mean pausing packet related Mods like Regen, so Blink could then no longer be used to escape from fights.

However, I might add another mod that pauses all packets, as it may be useful in other situations.

**Pull request closed without merging**
