### PR TITLE
Even Better Blink

### PR DESCRIPTION
**Pull request by HACKMC**
When a server teleports you somewhere and you are in blink, you don't physically stay where you were when you activated blink, blink still says you are where you started, but you are teleported with the server, it would be great if you could make server teleportation not effect the physical location of the player while blink is activated.

### CODE REVIEW

**Comment by liach** [comment]
Alex block this guy.

**Comment by HACKMC** [comment]
Ill just go to the suggestion website because I don't know how this works.....

Thanks for being an asshole liach

**Comment by Alexander01998** [comment]
@HACKMC
GitHub used to be our suggestion website, but I closed it some months ago and made https://feedback.wurst-client.tk to replace it.

I'm sorry that @liach was being rude to you. Unfortunately anyone can post anything on GitHub, which is one of the reasons why I'm no longer using it for suggestions.

**Comment by liach** [comment]
My bad.

**Comment by HACKMC** [comment]
@liach I feel bad too trust me, I get into these moments and have a bad time and I regret if I bothered you.

**Pull request closed without merging**
