### PR TITLE
Wurst is not 1.9.2 

### PR DESCRIPTION
**Pull request by KaboomCreepers**
**Wurst is not 1.9.2**
I cannot join servers that updated to 1.9.2 ;(

### CODE REVIEW

**Comment by kim-yannick** [comment]
@Alexander01998 could you delete the Auto-Crash-Reporting branch to prevent
people from abusing Pull Requests?
Am 17.04.2016 03:57 schrieb "KaboomCreepers" <notifications@github.com>:

**Comment by supertassu** [comment]
@KaboomCreepers Check Wurst-Impernium/Wurst-Client-for-MC-1.9.X

**Comment by mcccs** [comment]
https://twitter.com/Wurst_Imperium/status/717344257212817408

**Comment by Alexander01998** [comment]
> @Alexander01998 could you delete the Auto-Crash-Reporting branch to prevent
> people from abusing Pull Requests?

I hate deleting my code just because of spammers, but OK, that branch was broken anyways.

**Comment by Alexander01998** [comment]
I can't even do that anymore. It says that an open pull request depends on this branch even though it's closed.

cannot delete spam branch

**Pull request closed without merging**
