### PR TITLE
Fix autoleave for clans

### PR DESCRIPTION
**Pull request by mcccs**
I tested autoleave on Mineplex clans. Normal and chars mode didn't work.

### CODE REVIEW

**Comment by ThisTestUser** [comment]
Mineplex blocks special characters. If you see one of Alexander's hacking videos the accent words didn't go through.

**Comment by mcccs** [comment]
Oh yes

**Comment by kim-yannick** [comment]
I found out a (possible) way to let you being kicked. But does being kicked really bypass anti Logout plugins? If so, you could just force-end the connection to simulate a crash/internet problems.

**Comment by mcccs** [comment]
okay i have 2 acccounts, i will test and tell you.

**Comment by mcccs** [comment]
It didn't work. @kim-yannick

**Comment by kim-yannick** [comment]
My idea is this vanilla server code:

    if (Math.abs(packetIn.getPositionX()) > 3.0E7D || Math.abs(packetIn.getPositionZ()) > 3.0E7D) {
        this.kickPlayerFromServer("Illegal position");
        return;
    }

This kicks a player when a movement packet with a too high/low position is sent.

I think, this is in Spigot, too. Because it is vanilla, it maybe could also bypass NCP. I have not tried it yet.

**Comment by kim-yannick** [comment]
@ThisIsTestUser I'm currently not sure (I'm on my phone), but I think this check is executed before before the distance check.

**Comment by ThisTestUser** [comment]
The character kick is working because the server is kicking you, and combat logger is set to remove the tag when it detects that the server kicks you. Moving into an illegal position does work but there is no hack to teleport that works.

**Comment by kim-yannick** [comment]
I will try making it tomorrow. Like I said, I think the Illegal Position
kick is executed before checking the distance.

**Comment by mcccs** [comment]
I tested it using `.tp 200317+1 0 0`
Check distance works before.
That's why i didn't get kicked.

**Comment by kim-yannick** [comment]
At least in Vanilla (Look at NetHandlerPlayServer), the invalid position
check is executed before the distance check. If I look at the console,
there is no "Moved wrongly" or "Moved too quickly". I think just by doing
the teleportation with setPosition, some check on the client will prevent
the movement packet from being sent. I will check if sending a packet
manually will work. But first I am finishing the new ServerFinder.

2016-02-21 11:27 GMT+01:00 MCCCS <notifications@github.com>:

**Pull request closed without merging**
