### PR TITLE
NoOverlay

### PR DESCRIPTION
**Pull request by Nitrogen-Dioxide**
It disables fire overlay, water overlay, pumpkin overlay, sleeping
overlay, portal overlay, suffocating overlay (can be used for cave
finder) and warnings you if the mod list is in auto mode.

I'm having troubles with the patch file... so here the files that I changed in the Minecraft source.

https://www.dropbox.com/s/4s6pvtuni64qhqg/NoOverlay.rar?dl=0

### CODE REVIEW

**Comment by GlitchHead** [comment]
perfect for portal traps

**Comment by Nitrogen-Dioxide** [comment]
It only disables the overlay, not the "drunk" effect..

**Comment by eveythingistaken** [comment]
@Alexander01998 Why did you remove it? This is the most annoying thing ever for me. VV

screen shot 2015-05-08 at 2 30 34 pm

**Comment by Nitrogen-Dioxide** [comment]
@eveythingistaken He don't removed, I just don't know how to make the .patch file... This makes me angry :angry: .

**Pull request closed without merging**
