### PR TITLE
Added Wurst-specific Splash Texts

### PR DESCRIPTION
**Pull request by mcccs**

### CODE REVIEW

**Comment by mcccs** [comment]
Examples:
octocat loves meat
Server-finder vs https://minecraft.net/classic/list

**Comment by OMGchangeMYusername** [comment]
there are several grammar mistakes but well.. no one cares for splash texts after all..

**Comment by Alexander01998** [comment]
1. Changing the splash texts makes some things harder for contributors

2. I'd miss the normal splash texts

3. What @OMGchangeMYusername said

**Comment by mcccs** [comment]
Ok, have a nice day.

**Pull request closed without merging**
