### PR TITLE
Disenchanting is now possible using .enchant clear

### LINKED ISSUE #1833: .disenchant command
A command that remove's all encahntments of the current item (Creative)

### PR DESCRIPTION
**Pull request by kim-yannick**
Closes #1833. Also fixed a bug I found.

### CODE REVIEW

**Comment by Alexander01998** [comment]
Please separate this into two Pull Requests.
Just like Issues with multiple suggestions and bug reports, Pull Requests with multiple implementations and bugfixes are extremely confusing and tough to manage.

**Comment by kim-yannick** [comment]
But the bug is in the same file and its hard to change the same file using 2 pull requests because merging both will add conflicts.

**Comment by Alexander01998** [comment]
Well yes, but the way you are doing it, I don't know what code belongs to the .disanchant command and what belongs to the bugfix.

Not to mention that I don't even know what bug you are trying to fix. You're probably closing another Issue with that.

**Comment by kim-yannick** [comment]
The "bug" is that the enchantments are only modified on the client, which leads to fake enchantings/ghost items. My small fix is that the ItemStack is sent back to the server using the Creative Inventory Action Packet.

Maybe i could redo the pull request with 2 commits: One for the new feature and one for the bugfix. Would this be OK?

**Comment by Alexander01998** [comment]
> Maybe i could redo the pull request with 2 commits: One for the new feature and one for the bugfix. Would this be OK?

No. Make two Pull Requests.

**Comment by kim-yannick** [comment]
But how to change the same file in two PRs?
Am 15.08.2015 21:06 schrieb "Alexander01998" <notifications@github.com>:

**Comment by Alexander01998** [comment]
Just wait until I merge the first PR and then open the second one.

**Pull request closed without merging**
