### PR TITLE
Very small typo

### PR DESCRIPTION
**Pull request by ThisTestUser**
This is just a small typo to fix the Jesus mod description.

### CODE REVIEW

**Comment by ThisTestUser** [comment]
This is easy to fix. Just fix the "is" to "if" and thats it.

**Comment by ThisTestUser** [comment]
What is the error here? It's just changing the Jesus mod description from "is" to "if". This is the correct way to say it.

**Comment by Alexander01998** [comment]
> What is the error here? It's just changing the Jesus mod description from "is" to "if". This is the correct way to say it.

Your PR broke the "©" character in JesusMod.java by using a different encoding.

**Comment by ThisTestUser** [comment]
So how do I fix this?

**Comment by mcccs** [comment]
You can't.

**Comment by ThisTestUser** [comment]
So can you fix the typo?

**Comment by mcccs** [comment]
Only Alexander can.

**Comment by ThisTestUser** [comment]
Looks like I can't fix it without breaking the encoding, so can you just make the "is" an "if"?

**Pull request merged**
