### PR TITLE
Added 2 new AutoLeave/.leave modes

### PR DESCRIPTION
**Pull request by kim-yannick**
**The modes:**

 - TP: Teleports you out of the world border. Does not work with NCP.
 - SelfHurt: Tries to hit yourself. Bypasses NCP!

### CODE REVIEW

**Comment by kim-yannick** [comment]
Why is GitHub thinking the whole file changed everytime?

**Comment by Alexander01998** [comment]
> Why is GitHub thinking the whole file changed everytime?

Might be the line endings. Pretty sure mine are `\r\n`.

**Comment by kim-yannick** [comment]
@Alexander01998 Could I please get a Wurst Cape? I already contributed FancyChat, the base of the session stealer, .modify and .give. I'm also working on a new mod which is very OP on non-NCP servers (I will say what it does if it's released).

You don't need to, if you don't want. But I would like it. 

IGN: 1st account: kim_yannick, 2nd account: Vinctendo

**Comment by mcccs** [comment]
Also, Alexander, My Minecraft launcher always gives me this error:
```
[Wurst] Failed to load 2 cosmetic(s) from wurst-capes.tk!
Server response:
null
java.io.IOException: Server returned HTTP response code: 500 for URL: https://www.wurst-capes.tk/cosmetics/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at tk.wurst_client.utils.MiscUtils.post(MiscUtils.java:204)
	at tk.wurst_client.capes.CapeFetcher.run(CapeFetcher.java:55)
	at java.lang.Thread.run(Thread.java:745)
```
and wurst-capes.tk/cosmetics is blank

**Comment by Alexander01998** [comment]
The cape server is having a hard time keeping up with all the traffic, that's why it will give you an error sometimes. The hosting provider is currently having problems with the FTP server, so I can't make any changes to the Wurst Cape server or the Wurst Feedback site at the moment.

**Comment by kim-yannick** [comment]
Will I then get a cape? And what about SFTP (SSH FTP, works with all linux
servers that use SSH). WinSCP is a good free client that supports SFTP.

**Comment by Alexander01998** [comment]
It already is SFTP.

**Comment by kim-yannick** [comment]
My question is still not answered. I don't want to annoy, so if you don't want to, just say it.

**Comment by Alexander01998** [comment]
> My question is still not answered. I don't want to annoy, so if you don't want to, just say it.

At the moment, I can't. Later, maybe. Not for two accounts though, only one.

**Comment by Alexander01998** [comment]
OK, I have made a  decision. I wouldn't give you the normal Wurst cape, as that cape is only meant for Wurst-Imperium members. My plan was to make a contributor cape instead, but the problem with that is that ever contributor would then want a contributor cape.

I don't believe that the wurst-capes.tk server will survive very long and the json file on the Wurst website cannot handle a lot of capes (the file would get bigger, take longer to download and thereby slow everyone down).

Also, and this is the much bigger problem, people might start contributing just to get a cape, rather than contributing to improve the Wurst Client. That would likely lead to a lot of low-quality contributions.

Therefore, my decision is to not give you a cape. I know I could have just said "No" as you suggested, but I want to make clear that this is not a subjective decision and that there are actual reasons behind it.

**Comment by mcccs** [comment]
Alexander isn't Github a better host? If it is how about importing them to Github?

**Comment by Alexander01998** [comment]
> Alexander isn't Github a better host? And if it is, how about importing them to Github?

The thing is, GitHub Pages doesn't support PHP or MySQL. Things like the feedback site are impossible to build with GitHub Pages.

**Comment by kim-yannick** [comment]
BTW, I found a way to bypass Vanilla Fly Kick. PR is coming soon. I found this out while working on another big thing.

**Comment by kim-yannick** [comment]
I think the Flight bypass thing is done tomorrow. Will you add it to Wurst 2.18, too?

**Comment by Alexander01998** [comment]
> I think the Flight bypass thing is done tomorrow. Will you add it to Wurst 2.18, too?

Probably not. Wurst 2.18 already has a good amount of new stuff in it.

**Comment by kim-yannick** [comment]
@Alexander01998 Should I integrate the Fly kick bypass into Flight and JetPack or should I make an extra mod for the bypass? The reason why I'm asking this is, it causes fast regeneration, too, because of the many movement packets. On servers like Wizardhax (which is down currently), where Regen is not allowed, Flight would may cause a ban without being actually using Regen. Also, if the server already allows flying, the Flight and JetPack mods would cause a lot of unecessary traffic. But some new users may don't find the option and wonder why they are still getting kicked.

**Comment by Alexander01998** [comment]
Just add a checkbox to Flight and Jetpack so that the bypass can be toggled.

**Comment by mcccs** [comment]
@kim-yannick After you finish fly kick bypass, if you can't find any ideas, I invented how to use WallHackKillaura without **modifying source code**. 

1) Enable GhostHand
2) Enable Killaura
3) That's all!

The problem is 90 % of Wurst users don't know this and if they enable ghosthand, they'll be unable to place/break blocks. My idea is to merge them, but the user should be able to break/place blocks.

Evidence:
[(Click me if GIF doesn't load)](https://cloud.githubusercontent.com/assets/11584045/13258766/2bc6196c-da5d-11e5-83d9-87590441d5f7.gif)
WallHack

**Comment by kim-yannick** [comment]
I'm already working on two new big things.

**Comment by ThisTestUser** [comment]
Also, will the autosoup and auto(splash)potion be added? I made seperate pull requests of them, but the navigator "see also" will be broken in them, but other than that its ok.

**Comment by supertassu** [comment]
@ThisTestuser I think that you need to make pull requests for autosoup and autopot. :+1:

**Comment by ThisTestUser** [comment]
I don't want to take someone's code and pose it as mine, and also I can't clean up the code, so I'll just see if the original author responds.

**Comment by kim-yannick** [comment]
@Alexander01998 Is the Wurst download count real? It got from 3.124M to 3.125M in just a single reload. Are really that much people downloading Wurst?

**Comment by Alexander01998** [comment]
> Is the Wurst download count real? It went from 3.124M to 3.125M in just a single reload. Are really that much people downloading Wurst?

Of course it's real. You can check using the GitHub API: https://api.github.com/repos/Wurst-Imperium/Wurst-Client/releases

**Comment by mcccs** [comment]
i noticed it too. I guess the DL counter is updated per a minute.

**Comment by kim-yannick** [comment]
I can't find the info of the DL count on this page.

**Comment by MajesticMagician** [comment]
Can I please get some help with my problem? I messaged the email on Alexander01998 profile!

**Comment by supertassu** [comment]
@majesticmagician, what is your problem?

**Comment by MajesticMagician** [comment]
Every time I go to import the wurst project into eclipse to make some mods
or whatever, it doesn't show anything in the src folder.
And, when I link the folder, just like the tutorial says, it gives me more
errors rather than taking them away!
I don't have any idea what to do, and it confuses me...
Do you have any idea whats happening?

**Comment by MajesticMagician** [comment]
Not trying to pry but, is anyone there that can help me?

**Comment by MajesticMagician** [comment]
@supertassu Hello?

**Comment by supertassu** [comment]
@majestmagican, sorry, getten internet problems. I have no idea why getted it.

**Comment by ThisTestUser** [comment]
Well, you need screenshots, so press the prntscr key and show us what errors you get.

**Comment by MajesticMagician** [comment]
ok, thanks

**Comment by MajesticMagician** [comment]
Here is one... It shows how when I import wurst into eclipse, it doesnt show the src folder with anything in it! [http://imgur.com/Ou5noR8](url) Could anybody help?

**Comment by supertassu** [comment]
wurstfix
- Copy Red covered text, no `.git`
- File -> Switch Workspace
- Paste
- ok
- Done
@MajesticMagician

**Comment by supertassu** [comment]
@Majesticmagician Is it worked?

**Comment by ThisTestUser** [comment]
You need to link to .git, delete the Wurst project and redo the step.

**Comment by MajesticMagician** [comment]
I tried switching the workspace, but nothing shows up when i switch it. And when I switch to a clean folder, it does nothing when i import! Does somebody have, like, a skype or something, so i can work this out?

**Comment by supertassu** [comment]
-** Take a screenshot **

**Comment by MajesticMagician** [comment]
Sorry

**Comment by supertassu** [comment]
Ok. I updste my comments, read comments before doing everything.

**Comment by MajesticMagician** [comment]
Ok, so i tried to do this before, but when i did this, http://imgur.com/a/ChcoG

**Comment by MajesticMagician** [comment]
It did nothing, the src folder was left empty, and nothing worked afterwards

**Comment by MajesticMagician** [comment]
Can somebody give me a step-by-step tutorial on this, other than the one on the wurst website?

**Comment by MajesticMagician** [comment]
Hello?

**Comment by MajesticMagician** [comment]
Is anybody there?

**Comment by ThisTestUser** [comment]
Your "working directory" shown in screenshot 2 is not the same as shown in the second to last image, which means that you just created a blank project. To fix, the directory should be the one in the second image.
https://cloud.githubusercontent.com/assets/10100202/12976295/442ab650-d0c3-11e5-9603-671a6446fc9f.jpg
Do this, except name it Wurst Client instead of Wurst Client Clone.

**Comment by MajesticMagician** [comment]
I know I created a blank project. It's just that every time I import wurst to the workspace, it show nothing in the src folder!

**Comment by ThisTestUser** [comment]
Perhaps you need to restart. Navigate to the area where you placed your Eclipse workspace and delete the .metadata. Then, install github desktop and make your workspace at Documents/Github.

**Comment by MajesticMagician** [comment]
OK, but it will still give me that error, I reformatted my system trying to
get rid of it

**Comment by ThisTestUser** [comment]
By restart I mean to delete the .metadata and change the workspace.

**Comment by MajesticMagician** [comment]
Oh...

**Comment by MajesticMagician** [comment]
But would that get rid of the error?

**Comment by ThisTestUser** [comment]
Also, I get this error when I try to apply minecraft,patch.
http://i.imgur.com/RTTT7XU.png

**Comment by MajesticMagician** [comment]
Could someone please talk to me on skype?

**Comment by kim-yannick** [comment]
@ThisTestUser I think I got this patch error too. I think the missing changes are not that important, but I think I applied them manually, which works.

**Pull request merged**
