### PR TITLE
AutoSplashPot

### PR DESCRIPTION
**Pull request by Alexander01998**
Automatically throws splash potions.

### CODE REVIEW

**Comment by ThisTestUser** [comment]
Is it possible for you to fix the encoding, because I can't?

**Comment by GlitchHead** [comment]
this will be very useful for locking spawns with kill potions could you possibly convert this mod to auto right click on any item?

**Comment by ThisTestUser** [comment]
I didn't make this, you have to ask the original author (https://github.com/Wurst-Imperium/Wurst-Client/pull/2386)

**Comment by ThisTestUser** [comment]
Also, will this ever be added?

**Comment by MajesticMagician** [comment]
Please! I need help, please contact me on my skype, aaron17115, I am
TheMajesticMagician

**Comment by Alexander01998** [comment]
Merged.

**Pull request closed without merging**
