### PR TITLE
Add .modify command

### LINKED ISSUE #1946: .modify command
A command modify nbt data tags on current item (Creative)
.modify add {display:{Name:$4Name}}
.modify add {SkullOwner:Player}
.modify remove SkullOwner

### PR DESCRIPTION
**Pull request by kim-yannick**
It features 4 actions: add, remove, set and metadata.
Resolves #1946

### CODE REVIEW

**Comment by Alexander01998** [comment]
Please sign the CLA.

**Comment by kim-yannick** [comment]
CLA?

**Comment by mcccs** [comment]
Click the details button

**Comment by Alexander01998** [comment]
> CLA?

Contributor License Agreement. Basically an agreement stating that:

1. you are contributing this PR to the Wurst-Imperium and allow us to use it

2. you are allowed to contribute this PR to the Wurst-Imperium because you either made it or have permission from its creator.

**Comment by kim-yannick** [comment]
And how to accept the CLA?

**Comment by games647** [comment]
>And how to accept the CLA?

>Click the details button

**Comment by Alexander01998** [comment]
image

**Comment by kim-yannick** [comment]
OK, signed it. I hope Wurst will ever stay free.

**Comment by Alexander01998** [comment]
Alright, thanks!

**Pull request merged**
