### PR TITLE
Merge pull request #1 from Wurst-Imperium/master

### PR DESCRIPTION
**Pull request by ThisTestUser**
Title

### CODE REVIEW

**Comment by kim-yannick** [comment]
GitHub is so buggy.

**Comment by kim-yannick** [comment]
You can also see an Issue in the pulse, even if the issues are closed. I've seen multiple PRs which all have been buggy. What should the PR really be?

**Comment by ThisTestUser** [comment]
The PR was originally to update my branch so I could seperate autosoup and autopotion. It should have appeared on my fork but it appeared here instead.

**Comment by Alexander01998** [comment]
> The PR was originally to update my branch so I could seperate autosoup and autopotion. It should have appeared on my fork but it appeared here instead.

You shouldn't use PRs to update your Fork. Do a Merge or a Rebase instead.

**Pull request closed without merging**
