### PR TITLE
Paramount

### LINKED ISSUE #1972: Wurst doesn't bypass Paramount (Anti Cheat System) ?
Paramount is a anti cheating system like NoCheatPlus. Paramount created by Sir java. I just watched this video ( https://www.youtube.com/watch?v=r_IAxkQi_Z4 ) and Wurst's Killaura system seems doesn't work. Actually we don't need to break paramount now. It's not completed yet and all servers is still using NCP right now. But If paramount disables all hacked client's cheats (Killaura,Speed,Regen,Flight etc.)?  (I don't think Server owners will use paramount but We need to bypass this thing.)

(Paramount's anti cheat system on hacked clients)
Wurst by @Alexander01998 :https://www.youtube.com/watch?v=r_IAxkQi_Z4
Huzuni:https://www.youtube.com/watch?v=t7K5XwcUG_c
Wolfram:https://www.youtube.com/watch?v=_Aaxrrb1jxc
Metro:https://www.youtube.com/watch?v=l5EJBXMj6yU
Xenon:https://www.youtube.com/watch?v=kpVOq6z524A

We don't have the source code of Paramount now but when it relased. It will be so hard to break this 'AntiCheatSystem'.

You can watch the Saint vs. Paramount. (Detailed) 
https://www.youtube.com/watch?v=p6d3GVWZw3c

### PR DESCRIPTION
**Pull request by mcccs**
Attempt to fix #1972 Paramount's speed bypass

### CODE REVIEW

**Comment by pokeball99** [comment]
i think we need to have a different yescheat for each anti-cheating plugin,not just change it permanently in the source

**Comment by Alexander01998** [comment]
Paramount won't succeed, no need to worry about it.

I've seen so many of these seemingly perfect anti hack plugins that ended up getting abandoned after just a few weeks, before even being finished or being used anywhere.

**Comment by PixelMaster3D** [comment]
That's probably no one wants to pay for them.

**Comment by PixelMaster3D** [comment]
And noceatplus is common. All we have to do is wait till they become popular.

**Pull request closed without merging**
