### PR TITLE
Barrier Esp

### PR DESCRIPTION
**Pull request by Nitrogen-Dioxide**
@Alexander01998 Now I just need to generate a patch file like yours ( I can generate one, but without that information ):

    From 8cea61c207ad52415668e88e59079ad540a25d3c Mon Sep 17 00:00:00 2001
    From: Alexander01998 <contact.wurstimperium@gmail.com>
    Date: Mon, 7 Sep 2015 14:46:55 +0200
    Subject: [PATCH] Wurst
     ---
    .gitignore                                         |    3 +-
    src/net/minecraft/block/Block.java                 | 3034 ++++----
    src/net/minecraft/block/BlockCactus.java           |  305 +-
    src/net/minecraft/block/BlockLiquid.java           |  846 +--
    src/net/minecraft/block/BlockSlab.java             |  376 +-

I just want to know how you add that information :arrow_double_up:  .

### CODE REVIEW

**Comment by Alexander01998** [comment]
> I just want to know how you add that information  .

Git should add that automatically. Only the date and email address is different for you.

If it helps, I'm using this batch code to update the patch:

```batch
@echo off
rem Batch script for updating the Minecraft patch.
rem Requires a local repo with the Minecraft source code.
rem Branches:
rem master    vanilla MC 1.8.0
rem Wurst     modified Wurst MC
rem tmp       temporary branch (will be created & deleted automatically)
rem Change the paths to match your workspace layout.
W:
cd W:\Eclipse\Minecraft
git checkout master
git checkout -b tmp
git merge --squash Wurst
git commit -a -m "Wurst"
git format-patch master
git checkout Wurst
git branch -D tmp
move /Y 0001-Wurst.patch W:\GitHub\Wurst-Client\patch\minecraft.patch
rem pause
```

(save it as `update-patch.bat` and double click it)

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 

Thanks about the batch code! It helped me and generated the patch file, but there is a problem, it generates in a "different way" than yours ( smaller but with the same effects ).

I think that with this 2 screenshots you will understand what i'm saying.

Your patch file:


My patch file:

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 

Can you take a look at the patch file, this is the only way I could generate it.

**Comment by Alexander01998** [comment]
Your Git version is different. Mine is `2.0.0`, yours is `1.9.5.github.0`.
Other than that, I don't know what could could be wrong.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 

I changed the git version and it does the same effect. But you can use this patch file right?

**Comment by mcccs** [comment]
@Alexander01998 @Nitrogen-Dioxide both are outdated versions! https://git-scm.com/download/win

**Comment by Nitrogen-Dioxide** [comment]
@mcccs 

I generated one patch file with this version too and it does the following:
    
    2.5.2.windows.2

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 

Isn't it better to be generated this way? because the current patch have 6 MB it is a really huge file.

**Comment by mcccs** [comment]
Maybe the problem is in settings?

**Comment by Nitrogen-Dioxide** [comment]
This really pisses me off :anger: because without the patch file I can't contribute correctly to wurst.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 

Ok... I'l try one more time (  the 7 time I think xD ), how do you commit to your mcp local repository? Is it through GitHub or through the console? if it is through console (or even eclipse) please tell me, because I think that they commit in different ways. Oh, if you commit through the console tell me too.

**Comment by Alexander01998** [comment]
> how do you commit to your mcp local repository? Is it through GitHub or through the console?

I use Eclipse for that. Select the modified files in the Package Explorer and press <kbd>Ctrl</kbd> + <kbd>#</kbd>.

**Comment by Nitrogen-Dioxide** [comment]
I just tried a lot of ways to generate this patch... I'm just exhausted now, well, I wish I could do a lot of additions to the client, but I can't.

**Pull request closed without merging**
