### PR TITLE
More AltManager enhancements

### PR DESCRIPTION
**Pull request by Alexander01998**
Tacos :heart:

### CODE REVIEW

**Comment by Notchshero** [comment]
Will these fixes come in a new update?

**Comment by Alexander01998** [comment]
> Will these fixes come in a new update?

That's what merging Pull Requests is there for. :wink: 

More info about how GitHub works can be found [here](https://guides.github.com/introduction/flow/).

**Comment by GlitchHead** [comment]
the converter.jar deleted me alts.wurst and did not create alts.json 1.6 ver.....

**Comment by Alexander01998** [comment]
> the converter.jar deleted me alts.wurst and did not create alts.json 1.6 ver.....

That's awkward. It was programmed to only delete the old alt list *after* successfully creating the new one. Are you sure about this?

**Comment by GlitchHead** [comment]
yes i select the directory alts.wurst is in click next thing in converter it says reading alt list and deletes alts.wurst and there is no alts.json nothing. i checked the directory if it was hidden.. it was not there.

**Comment by GlitchHead** [comment]
Error Log using java -jar Converter.jar
http://pastebin.com/1dcqgi7U
it says Done converting and that error comes up in console

**Comment by GlitchHead** [comment]
i managed to make it convert by removing all cracked alts... now when i put alts.json in the wurst folder and start wurst it says you have a empty alts list

**Comment by GlitchHead** [comment]
turns out... the wurst client wont even read the alts.json i select create random alts and restart client and im prompted to create random alts again and the list is empty.

**Comment by Alexander01998** [comment]
Should be patched now. I updated the Alt class to the one used in the final release of Wurst v1.6.

**Comment by GlitchHead** [comment]
still not being read in v1.6.1 o_O

**Comment by Alexander01998** [comment]
Your encryption key might be broken. Try deleting the `key` file and converting your alt list again.

**Comment by GlitchHead** [comment]
were is the key?

**Comment by GlitchHead** [comment]
i deleted the whole wurst folder and restarted minecraft still alts will not be read

**Comment by GlitchHead** [comment]
even ones i create in the alt manager they will no be there on restart

**Comment by GlitchHead** [comment]
were is the key file located?

**Comment by Alexander01998** [comment]
> were is the key file located?

The AES key (which I told you to delete) is at `.minecraft\wurst\key`. The two RSA keys are at `C:\Users\You\.ssh\wurst_rsa` and `C:\Users\You\.ssh\wurst_rsa.pub`. The AES key is required to read/write the alt list and the RSA keys are required to read/write the AES key.

If you can, debug c0337d60424ad0cc4cd3195a314da67b1f01a158 in Eclipse. That version will log any exceptions it gets while loading/saving the alt list.

**Comment by GlitchHead** [comment]
i dont have .minecraft/wurst/key or .ssh/wurst_rsa .ssh/wurst_rsa.pub
could it be not working because it wont create them?

**Comment by Alexander01998** [comment]
Then it couldn't even create `alts.json`.

**Comment by GlitchHead** [comment]
then any other ideas were wurst_rsa or wurst_rsa.pub would be?

**Comment by GlitchHead** [comment]
i have linux so where would wurst put the files?

**Comment by Alexander01998** [comment]
It uses the `user.home` system property and appends `\.ssh` to it. On Windows, this turns into `C:\Users\You\.ssh`. It's probably a different location on Linux. And if I remember correctly, Linux turns all folders that start with a dot into hidden folders.

**Comment by GlitchHead** [comment]
there is still no /home/(me)/.ssh/wurst_rsa :C when i do "echo user.home" i get .home so were would it be going there is no directory .home i think

**Comment by Alexander01998** [comment]
Like I said, it's a hidden folder on Linux. Make sure that you can see hidden folders.

**Comment by GlitchHead** [comment]
i cant goto the hidden directory /home/steven/.ssh
i can goto the hidden directory /home/steven/.minecraft

**Comment by GlitchHead** [comment]
well there is no directory /home/steven/.ssh

**Comment by GlitchHead** [comment]
there is not even that .minecraft/wurst/key file thing

**Comment by GlitchHead** [comment]
A HA!

**Comment by GlitchHead** [comment]
ERROR: http://pastebin.com/zdJmRJCp

**Comment by Alexander01998** [comment]
>well there is no directory /home/steven/.ssh

Maybe this happened:

1. The converter generated the RSA keys
2. It tried to save them to `System.getProperty("user.home") + "\.ssh"`, but that failed because the property doesn't exist on your computer.
3. Because it still had the RSA keys in the RAM, it was able to continue as if nothing happened.
4. It created `wurst\key` & `wurst\alts.json` properly.
5. You started Wurst.
6. Wurst couldn't find the RSA keys, so it generated new ones.
7. It tried to decrypt the AES key with the fresh RSA keys, but that failed.
8. It couldn't load the alt list either, so it just left it empty.

**Comment by GlitchHead** [comment]
its trying to goto /home/steven/.ssh
but its doing /home/steven\.ssh\wurst_rsa.pub

**Comment by Alexander01998** [comment]
> ERROR: http://pastebin.com/zdJmRJCp
>>`/home/steven\.ssh\wurst_rsa.pub (Permission denied)`

You don't have write access there.

**Comment by GlitchHead** [comment]
its trying the \ instead of /

**Comment by GlitchHead** [comment]
linux its /

**Comment by Alexander01998** [comment]
> its trying the \ instead of /
> linux its /

But why does it say `Permission denied` instead of `Invalid URI syntax`?

**Comment by GlitchHead** [comment]
idk

**Comment by GlitchHead** [comment]
it "thinks" its being denyed?

**Comment by Alexander01998** [comment]
Let's open an Issue for that in the Linux repo. :joy:

**Comment by GlitchHead** [comment]
am i doing that? just create a issues called Linux repo or something?

**Comment by Alexander01998** [comment]
Which version of Linux are you using?

> am i doing that? just create a issues called Linux repo or something?

I didn't get that question.

**Comment by GlitchHead** [comment]
what do you mean "Let's open an Issue for that in the Linux repo."

**Comment by Alexander01998** [comment]
> what do you mean "Let's open an Issue for that in the Linux repo."

Linux is an open source project with a repository on GitHub.
We just found a bug in Linux and we can report that bug by going to the Linux repo(sitory) and opening an Issue, just like you would report a bug in Wurst.

**Comment by Alexander01998** [comment]
However, there are many different versions of Linux (like Torvalds Linux, RedHat Linux, etc.) that all have their own repo.

So which version are you using?

**Comment by GlitchHead** [comment]
kali linux

**Comment by GlitchHead** [comment]
but is there a fix you can do to the client? just asking.

**Comment by Alexander01998** [comment]
> but is there a fix you can do to the client? just asking.

Yup.
Take a look at [FileManager.java (lines 48-62)](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/Wurst%20Client/src/tk/wurst_client/files/FileManager.java#L48-L62). It specifies the location of its files using `new File(File parent, String child)`.
[Encryption.java (lines 43-44)](https://github.com/Wurst-Imperium/Wurst-Client/blob/master/Wurst%20Client/src/tk/wurst_client/alts/Encryption.java#L43-L44) specifies it's file locations using `new File(System.getProperty("user.home") + "\\.ssh\\wurst_rsa")`.
So all I need to do is change Encryption.java to use the same method as FileManager.

**Comment by GlitchHead** [comment]
:D

**Comment by GlitchHead** [comment]
is this going to be in the next wurst update?

**Comment by GlitchHead** [comment]
in the next update will this be fixed? just want to know.

**Comment by Alexander01998** [comment]
> is this going to be in the next wurst update?
> in the next update will this be fixed? just want to know.

Yes, obviously.

**Comment by GlitchHead** [comment]
Lel

**Pull request merged**
