### PR TITLE
Bounds checking for GUI elements.

### PR DESCRIPTION
**Pull request by null-dev**
I have completed the fix for the bug I emailed to you.

It's all up to you now :).

Bug Details:
GUI elements pertaining to the highlighted element stay highlighted even after the element is removed. This pull request fixes this.

### CODE REVIEW

**Comment by null-dev** [comment]
Can you give me a hint to what is broken? (I sort of wrote these commits in the online editor instead of my IDE).

**Comment by null-dev** [comment]
Ok, I think I have resolved the formatting issues, just tell me if you have any more suggestions.

**Comment by mcccs** [comment]
I guess this solves #1815

**Comment by null-dev** [comment]
No it doesn't actually. It only resolves the problems for the GUIs in the
options screen. I will look into that though.

**Comment by Alexander01998** [comment]
> Ok, I think I have resolved the formatting issues, just tell me if you have any more suggestions.

Formatting issues are still there (see [line 2](https://github.com/Wurst-Imperium/Wurst-Client/pull/2347/files#diff-0d1f7aa67054409c0d619348cd259d4dR2)). What you changed would have been `clean up required`. I have changed the name of this label to `broken encoding` to avoid future confusion.

**Comment by null-dev** [comment]
Ok, I cannot figure out these formatting problems...
I honestly don't have time to fix all this formatting over 2 lines of code.
If they are still not fixed (and I think I messed up the import order with the last commit too), you are welcome to just close this PR and apply the changes manually. It's only 2 lines of code changed anyways I think.

**Comment by Alexander01998** [comment]
No problem, I can fix that.

This label is basically just a reminder for me so that I won't forget to replace the awkward `Â©` with a normal `©`.

**Pull request closed without merging**
