### PR TITLE
Create ZoomMod.java

### PR DESCRIPTION
**Pull request by mcccs**
Needs to be tested.

### CODE REVIEW

**Comment by GummiBoat** [comment]
> public class FullbrightMod

Line 22, you have ZoomMod, not FullbrightMod.

Also, @Alexander01998 cleary rejected this in #324.

**Comment by mcccs** [comment]
Alexander said it makes lagg, but look at my code, it is a small code.

**Comment by GummiBoat** [comment]
He did not said it makes lagg, he straight out rejected it.

**Comment by mcccs** [comment]
:frowning:

**Comment by OMGchangeMYusername** [comment]
Yep, it could be useful after all.

**Pull request closed without merging**
