### PR TITLE
No more Vanilla Fly Kicks

### PR DESCRIPTION
**Pull request by kim-yannick**
This feature works by instantly teleporting down and up in the same tick. It works up to a flying height (from ground up) of 300 blocks. Maybe more would work too, but I think this is too risky. It includes a new event, which needs changes to made in the vanilla code. More info about this is in the commit description. There is a new checkbox in both FlightMod and JetpackMod which can be used to disable this feature, because it causes faster regeneration, more traffic and no fall damage too.

flightmod

The [Kick: Safe] shows if the player is in a non-kickable height. If the player is too high, [Kick: Unsafe] shows right after the mod name, which means that the player can get kicked.

Please not that this feature won't work everytime (but this is very rare, mostly because of server lag or flying out of the loaded chunks). Also, there is no check about the block at the bottom (which can be fixed). Flying over Fire/Lava causes damage, items on the ground will be collected and so on. However, other players should not see you moving downwards/upwards. They think you don't change the position.

### CODE REVIEW

**Comment by supertassu** [comment]
:+1:. Good work.

**Comment by kim-yannick** [comment]
By the way, maybe someone should change "Vanilla" into something other, because it works on Spigot and CraftBukkit without AntiCheat, too.

**Comment by kim-yannick** [comment]
@supertassu Thanks

**Comment by kim-yannick** [comment]
Oh, and I forgot to mention: You'll need to change field_149474_g in C03PacketPlayer.java from protected to public.

**Pull request merged**
