### PR TITLE
Add .repair command

### LINKED ISSUE #1918: .repair command
Command to repair damaged items (Creative)

### PR DESCRIPTION
**Pull request by kim-yannick**
Repairs held items in creative. Resolves #1918

### CODE REVIEW

**Comment by Eyremba** [comment]
Yes! :D Pretty cool. @Alexander01998 could you add this also to Wurst 2.3?

**Comment by mcccs** [comment]
please add name history too.

**Comment by Eyremba** [comment]
Yes @mcccs #1377 would be nice in Wurst 2.3

**Comment by Eyremba** [comment]
@Alexander01998 could this be merged before the release of Wurst 2.3 or will you implement it in Wurst 2.4?

**Comment by nerdtron123** [comment]
+1

**Comment by Alexander01998** [comment]
Merged.

**Comment by mcccs** [comment]
No its not merged

**Comment by Alexander01998** [comment]
Yes it is.

**Comment by mcccs** [comment]
Oh i see now

**Pull request closed without merging**
