### PR TITLE
.annoy delay

### PR DESCRIPTION
**Pull request by wkuba500**
Delay for annoy. Please someone kill me.

### CODE REVIEW

**Comment by wkuba500** [comment]
What is the correct encoding for wurst client?

**Comment by mcccs** [comment]
Windows 1252 but ISO-8859-1 works too. @wkuba500

**Comment by wkuba500** [comment]
All files in wurst client has ANSI encoding so I've changed it to ANSI

**Comment by wkuba500** [comment]
Now if admin send fake message - for example from script it will not work.
Wurst is joking from server. Server can't joke from Wurst :P

**Comment by wkuba500** [comment]
Fixed converting. Thanks @ebildude123

**Comment by ThisTestUser** [comment]
This does not work.
Syntax error on token "catch", finally expected
	Syntax error on token "delay", delete this token
	Syntax error on token "else", delete this token
	Type mismatch: cannot convert from null to int
	Syntax error on token "}", delete this token
	The operator != is undefined for the argument type(s) int, null
	The operator != is undefined for the argument type(s) int, null
	The operator != is undefined for the argument type(s) int, null
Eclipse showed these errors while I tested the code, and running the client with the annoy delay resulted in a crash.

**Comment by mcccs** [comment]
@wkuba500 PR in my [repository](https://github.com/00AdvancedWurstCommunity/Wurst-Client-for-MC-1.9.X/edit/Annoy/Wurst%20Client%20for%20MC%201.9.X/src/tk/wurst_client/commands/AnnoyCmd.java?pr=/Wurst-Imperium/Wurst-Client-for-MC-1.9.X/pull/1) Mine is on the new repository.

**Comment by wkuba500** [comment]
Poor annoy delay ;(

**Comment by ThisTestUser** [comment]
This does not work.
There are still errors, and even if you correct them, the Thread.Sleep will make the entire client freeze for that amount of time.

**Pull request closed without merging**
