### PR TITLE
Make Blink auto-disable after 3000 ms is YC+ is enabled

### PR DESCRIPTION
**Pull request by FlareHAX0R**
Title says it all ^_^

### CODE REVIEW

**Comment by Eyremba** [comment]
What the fuck? Blink works also on NCP servers for around ~30 seconds. BAD IDEA @FlareHAX0R!

**Comment by FlareHAX0R** [comment]
@Eyremba I'll work on a 'toggle' for the time. Also, any website that claims this?

**Comment by FlareHAX0R** [comment]
@Eyremba 
"Blink will now display the number of milliseconds it has been active. This is useful on NoCheat+ servers, as they only allow you to Blink for 3000 milliseconds. This was implemented by a contributor in Pull Request #2185. The same contributor also fixed .blink on and .blink cancel causing problems when being activated too quickly." ~ https://www.wurst-client.tk/news/2015-09-11-Wurst-2-4-released/

I also attempted to do it for 6 secs on a NCP server, it didn't work.

**Comment by Nitrogen-Dioxide** [comment]
@FlareHAX0R 

Make blink modes is better, when I finish barrieresp I'll start working on it.

**Comment by FlareHAX0R** [comment]
Eclipse just finished downloading, so I think I'll work on it right now :)

**Comment by FlareHAX0R** [comment]
@Nitrogen-Dioxide I made auto mode for you :P

**Comment by Eyremba** [comment]
I don't know whats wrong with you guys. On the NCP testserver with the newest NCP version I can blink up to 15 seconds. This also depends on your internet connection.

**Comment by FlareHAX0R** [comment]
@Eyremba I guess it varies. With this push, you can do .blink max (ms)

**Comment by FlareHAX0R** [comment]
(note: automode is only when YC+ is active. if you dont need it, just set it to like 30000000000)

**Comment by Nitrogen-Dioxide** [comment]
@Eyremba 
Go to guild craft, wal craft

wal craft is 4000 ms

**Comment by Eyremba** [comment]
I tested Wurst 2.5 against the newest NCP version, and blink worked for 7 seconds. So 3 sec. is really to less. Also, if you make it, make it as an option, so that the "normal" mode can still be used.

**Comment by FlareHAX0R** [comment]
@Eyremba  You can configure it, and if you don't like it, just set the max time to something huge.

**Comment by FlareHAX0R** [comment]
Is this gonna be pending forever? >_<

**Comment by PixelMaster3D** [comment]
@FlareHAX0R that depends on when @Alexander01998 is feeling that is a good enhancement.

**Comment by mcccs** [comment]
I think it must be min. 10000 ms

**Comment by Alexander01998** [comment]
Judging by the comments, the amount of time you can use Blink on NoCheat+ can vary a lot.
Therefore it's probably not a good idea to limit the time in Wurst.

**Comment by FlareHAX0R** [comment]
Thats... why I added confiruable time.

**Pull request closed without merging**
