### PR TITLE
Create CrashCmd.java

### PR DESCRIPTION
**Pull request by mcccs**
Sends a character that crashes tr-TR clients.

### CODE REVIEW

**Comment by 1337HaxorKiddie** [comment]
The syntax string should be: "No Arguments needed" and the name shlud be: "Turk Crash" or something like that bc Crsh is not really the best name.

**Comment by GummiBoat** [comment]
... how is this supposed to work exactly? `if(args.length != 0)` this says, "If there are arguments, then..." and the else statement ("if there are no arguments") says `syntaxError("Arguments not needed.");`.

Sorry, but... did you tested this?

**Comment by OMGchangeMYusername** [comment]
@GummiBoat just to be a bitch, "did you" come with bare infinitive of the verb :heart:

**Comment by mcccs** [comment]
@GummiBoat Ehh. You're right

**Pull request closed without merging**
