### PR TITLE
Canbefaced method for NukerLegit

### PR DESCRIPTION
**Pull request by Nitrogen-Dioxide**
I learned a bunch of things about Java programming these days, now I know how to use switch and make static methods xD.

Well, It was not so easy than I though to make this method :/, but I find out how Minecraft calculate the light from an block.

Oh, the reason that I made that, is because NukerLegit try to mine blocks that you can't see (inside walls) , making it very easy to get you banned.

It checks the light of the block that NukerLegit targets, making it
"more legit" by don't breaking blocks that are inside walls. 

cabefaced_40

And there is a bonus : 
it doesn't mine if the block is with light 0 too, making "suspicious darkness mining" less noticeable.

I made it display a chat message to see how it is working (only for debug, must remove it).

Hope you like it.

### CODE REVIEW

**Comment by Alexander01998** [comment]
Determining whether or not a block is inside of a wall based on its light level is good for the performance (you don't need to check the surrounding blocks), but it is often impractical for mining, as users will usually be mining in a dark place and using Fullbright instead of torches.

I have an idea that would fix both problems (performance and accuracy) by using *breadth first search* to find the block, but that's a different story.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 Yea I noticed that if a block is under a transparent block, the light on it will be 15 on the surface :/.

And what do you mean about breadth first search?

**Comment by Alexander01998** [comment]
> And what do you mean about breadth first search?

[Breadth first search](http://en.wikipedia.org/wiki/Breadth-first_search) is a searching algorithm that can be used to quickly find the nearest reachable block. It should be even faster than the method that I'm currently using.

**Comment by Nitrogen-Dioxide** [comment]
Oh, so your idea, is make an array (or tree) and mine the blocks that have the same ID (in id mode) and that are don't surrounded by other blocks?

**Comment by Alexander01998** [comment]
I improved the order in which the blocks are being processed. The closest blocks will be processed first, so it is no longer necessary to calculate which block is the closest.
[](http://en.wikipedia.org/wiki/Breadth-first_search)
And by only checking for adjacent blocks if the current block is air, blocks inside of walls will be ignored.

**Pull request closed without merging**
