### PR TITLE
AutoPot & AutoSoup

### PR DESCRIPTION
**Pull request by Ceiridge**
Hey,
in my repo I have added autosoup & autopot and I'd be if it is going to be added :).
Keep in mind that some commits are a bit buggy (github made the errors!) (e. g. the "delete-everything and add-everything")

A lot of people wanted autosoup & autopot (look at your comments ;) ) so I think they will be happy.

### CODE REVIEW

**Comment by Alexander01998** [comment]
Please split those features into separate Pull Requests.

**Comment by kim-yannick** [comment]
Also, please do not include your custom README. This messes up the Repo. Also, only include the files that are necessary for your new feature, such as the Mod itself and the changed ModManager. If you split it, you have to create a seperate branch for both mods. Don't include both mods in a single ModManager! This is a common fault, as moving into another branch does not remove untracked files.

**Comment by Alexander01998** [comment]
Exactly.

**Comment by Ceiridge** [comment]
Okay, I'm sorry. I'm going to make it better in the future

**Comment by kim-yannick** [comment]
Okay

**Comment by ThisTestUser** [comment]
So if it works, would it be implanted? This would make Wurst work for kitpvp.
Also, autopot actually is supposed to automatically drink healing potions, so you should make an autosplashpot (what you have) and autopot (automatically drinks potions).

**Comment by Ceiridge** [comment]
@ThisTestUser He didn't merge it and  closed the pull, so I don't think that it'll be in the original version. But maybe he'll implement it manually. :)
Maybe later if he won't implement it then I'm going to pull it again but followed by the instructions (new branch, one commit only, etc.)

**Comment by kim-yannick** [comment]
I don't think he is doing it for now. Just clean up your code, use seperate
branches and don't fail at Git. Then he will accept it.

**Comment by Ceiridge** [comment]
@kim-yannick Yes, I know. But I have problems with git. When I make a new branch and I only want that one commit should be pulled then all commits are in the branch and I can't pull only one commit :(.

Dis English very gud

**Comment by Alexander01998** [comment]
> I don't think he is doing it for now. Just clean up your code, use seperate
> branches and don't fail at Git. Then he will accept it.

^

**Pull request closed without merging**
