### PR TITLE
Deathkit added.

### PR DESCRIPTION
**Pull request by FlareHAX0R**
Auto-executes a command on death.
Good for KitPVP.

(THIS WILL AUTOMATICALLY TURN OFF AUTORESPAWN, as this also automatically respawns.)

Example:
Bob sets DeathKit to the command '/kit starter'
Bob goes into PVP and dies
Bob respawns and gets the kit immediatly.

### CODE REVIEW

**Comment by FlareHAX0R** [comment]
Could someone test this for me? I can't do it because the minecraft.patch won't apply to the MCP output.

**Comment by ex0rpass** [comment]
holy crap that is awesome

**Comment by FlareHAX0R** [comment]
:) Thanks

Oh, and the command is selected in an easy to use GUI.

**Comment by GyselAnimatioon** [comment]
This is INSANE!!

**Comment by FlareHAX0R** [comment]
Did anyone test it?

**Comment by Alexander01998** [comment]
The same effect can already be achieved by using the `death.wspam` script.

**Comment by FlareHAX0R** [comment]
Did not know that. Sorry :(

**Pull request closed without merging**
