### PR TITLE
Created SessionStealer

### LINKED ISSUE #1029: Sessionstealer (Accountstealer)
Garploit 1.3 has a Sessionstealer :/ can this be added to wurst too?
https://www.youtube.com/watch?v=NsOGHuPn7Mg
30:12

### PR DESCRIPTION
**Pull request by kim-yannick**
Closes #1029

### CODE REVIEW

**Comment by mcccs** [comment]
Thx for PR

**Comment by GlitchHead** [comment]
i really think you should just edit the add alt section so it can accept a password or a session id
and the account with the session id will be added to your alts list.

**Comment by kim-yannick** [comment]
@mcccs But almost everyone does upload its log into pastebin. And other sites may not contain useful logs.

@GlitchHead Session IDs are not long lasting. So you don't need to add an alt with them. And it needs to be a seperate button, because passwords can not be distingushed from session tokens.

**Comment by kim-yannick** [comment]
@mcccs Oh, your'e right. I'll try to change that soon.

**Comment by mcccs** [comment]
@kim-yannick Next time could you please implemet #1377 works like the same

**Comment by kim-yannick** [comment]
@mcccs Tomorrow i am going to travel for about two weeks. I don't know if i can code if i'm there. But this will be easy because the json fetching and parsing can use the same code like you said.

**Comment by Alexander01998** [comment]
I couldn't get this to work yet. Whenever I try to join a premium server, it says that the session is invalid.

**Comment by kim-yannick** [comment]
Try looking for a session that is not old and should work. Maybe your session id is outdated.

**Comment by Alexander01998** [comment]
I tried a bunch of them but none worked. Do you have a working one for me?

**Comment by PixelMaster3D** [comment]
I found one to. But haven't tried yet.

**Comment by PixelMaster3D** [comment]
Typo

**Comment by GummiBoat** [comment]
Try one of [these](http://pastebin.com/eS4e4Hi5).

**Comment by kim-yannick** [comment]
Can you try starting vanilla MC and use the session id of your private log? If that does not work i have to look for issues. Maybe the default maximum input length of 32 chars cannot fit all tokens. You can look for that. For me it worked.

**Comment by PixelMaster3D** [comment]
Here's one: http://pastebin.com/ANv5bXj4

**Comment by Spassvogelw** [comment]
I tried some of GummiBoats list, but it did not work.
But I found another session id which works for me : http://gaming.stackexchange.com/questions/231841/my-minecraft-keeps-crashing-after-like-25-seconds-of-running
Strange that many of the tokens are not working, although they are new...

**Comment by GummiBoat** [comment]
Yeah, I don't want to start GarPloit to check them again. I'll update that list the next few days or so.

**Comment by Spassvogelw** [comment]
That would be fantastic. 
@PixelMaster3D The session ID you shared is not working for me either.  :(

**Comment by Alexander01998** [comment]
> But I found another session id which works for me : http://gaming.stackexchange.com/questions/231841/my-minecraft-keeps-crashing-after-like-25-seconds-of-running

That one worked.

**Comment by PixelMaster3D** [comment]
Must be outdated. The ID.

**Comment by mcccs** [comment]
i think [these](https://www.google.com/search?q=%22session+id+is+token%22&tbs=qdr:m#q=%22session+id+is+token%22&newwindow=1&tbs=qdr:d) must work

**Comment by kim-yannick** [comment]
@mcccs But sometimes older IDs also work. 24 hours is too less results. I think a week would be better.

**Comment by pokeball99** [comment]
Something in here could explain why some work and others don't

http://wiki.vg/Query#Generating_a_Session_ID

**Comment by Grievus** [comment]
Can you make a button to reset the id and turn it into your own so you can play with your account after you were uing the account of someone else?

**Comment by Alexander01998** [comment]
> Can you make a button to reset the id and turn it into your own so you can play with your account after you were uing the account of someone else?

Just add your own account to the Alt Manager and use it from there.

**Comment by OMGchangeMYusername** [comment]
Issues are gone :(

**Comment by PixelMaster3D** [comment]
Ik.

**Comment by Eyremba** [comment]
Yes issues are gone and I have also no access to them :(

**Comment by Alexander01998** [comment]
> Issues are gone :(

https://twitter.com/Wurst_Imperium/status/633312826006851584

**Comment by GlitchHead** [comment]
Bye everyone have a nice life!!!!!!!!

**Comment by Alexander01998** [comment]
I just want a little bit of silence so I can work on Wurst.

**Comment by BLUEGAMEftw** [comment]
it wont work PLSS HELP




PLSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

**Comment by BLUEGAMEftw** [comment]
[URL=http://media.photobucket.com/user/paigeylicious14/media/moving/l_d8d6e48f4a56e2a97dd6b963c783281c.gif.html][IMG]http://i192.photobucket.com/albums/z97/paigeylicious14/moving/l_d8d6e48f4a56e2a97dd6b963c783281c.gif[/IMG][/URL]

**Comment by BLUEGAMEftw** [comment]
helpp plsss

**Comment by EnderGamer21** [comment]
uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by EnderGamer21** [comment]
l

**Pull request merged**
