### PR TITLE
Add PotionCmd

### LINKED ISSUE #672: Potion Enchantments
A possible suggestion is to add a feature (like .potion) that can enchant potions with potion enchantments(i.e. blindness, speed, resistance, night vision, etc.) similar to how .enchant enchants items with item enchantments (i.e. sharpness, unbreaking, protection, etc.).  Then, as far as which enchantments would go on said potion, there could possibly be commands such as
.potion add (enchantment)  and  .potion remove (enchantment).

### PR DESCRIPTION
**Pull request by Huanjohn**
Adds the Potion Command, which can be used to change the effects of the held potion, if the user is in creative mode. This command can accept arguments in groups of 3.
i.e.  `.potion set 14 0 60 5 24 75` would set the held potion's effects to invisibility for 60 seconds and strength 25 for 75 seconds.
Resolve #672

### CODE REVIEW

**Comment by pokeball99** [comment]
Unless this is in survival,this is useless as u can just use /effect

**Comment by Bluscream** [comment]
+1 Approve Dont you need OP for /effect? This would work in gamemode,

**Comment by GummiBoat** [comment]
#342 will be able to do exactly this.

**Comment by Bluscream** [comment]
But #342 is a suggestion. Just words and whishes written down. #1305 is a Pull Request. Finished code that we just have to merge to make more skids happy.

**Comment by mcccs** [comment]
Thx huahjohn, u r the best "pull"er!

**Comment by Huanjohn** [comment]
@GummiBoat True, however this is a *much* more simple and compact way of doing so, allowing for many more effects to be given to the potion, due to the size limit in the chat bar; as #342, being as it would probably be made to work with all items and their nbt data, would likely require something similar to:
`.give potion 1 0 {CustomPotionEffects:[{Id:1,Amplifier:2,Duration:100},{Id:5,Amplifier:4,Duration:60}]}`
Which wouldn't even be able to fit in the chat bar.
With the addition of needing to multiply how many seconds you want the effects to last by 20, as Duration's unit is not accepted in seconds in the nbt data.

While this would only require: `.potion 1 2 5 5 4 3`, easily fitting into the chat bar, to make the same potion, allowing for the use of many more effects, and a *much* less tedious task, while allowing the Duration to be specified in actual seconds.

In other situations, the Give Command does work quite nicely, though.
I am enjoying using it.

**Comment by Bluscream** [comment]
@Huanjohn can you give me the compiled verion including you pull? I failed to get a minecraft eclipse environment runnig.

**Comment by GummiBoat** [comment]
@Huanjohn I don't think, that @Alexander01998 will run the .give command completely through the chat bar, because the chat bar is way to small for complex nbt data. But well, I personally don't care if this gets added or not. Good work tho.

**Comment by ravenje** [comment]
Or @Alexander01998  can add a new button in the fun menu that display a menu:
[Effect textbox] [Time textbox] [Power textbox] [HIde Particles button]
[Add button]

**Comment by Bluscream** [comment]
https://github.com/DavidGoldman/NBTEdit

**Comment by Alexander01998** [comment]
Needs support for potion effect names, e.g.: `.potion set invisibility 0 60`

**Comment by mcccs** [comment]
@Huanjohn ^

**Comment by Huanjohn** [comment]
You can now specify potion effects by their names (actual and similar).

**Comment by EnderGamer21** [comment]
ur da best u almost made wurst 2.2 by suggesting this

**Comment by GlitchHead** [comment]
is this going to remove particles? you can obtain effects with no particles with /effect

**Comment by Alexander01998** [comment]
> is this going to remove particles?

I don't think so, it just modifies potions.

**Pull request merged**
