### PR TITLE
Blink enhancement

### PR DESCRIPTION
**Pull request by Nitrogen-Dioxide**
2 fixes and distance traveled is now displayed.

### CODE REVIEW

**Comment by Eyremba** [comment]
Please can you also make it display the miliseconds how long you are blinking? This is also useful in some situations.

**Comment by Alexander01998** [comment]
I think it should display the number of milliseconds rather than the distance traveled, as only the time is limited on NoCheat+ servers.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 
@Eyremba 
Ok I'll change it.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 
Don't merge it yet because I'm planing to make .blink mode auto and manual.

**Comment by Alexander01998** [comment]
> Don't merge it yet because I'm planing to make .blink mode auto and manual.

Please do that in a separate Pull Request.

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 
Oh right haha

**Comment by Alexander01998** [comment]
> Clean up …
> Missed to import format configurations.

I was just about to say that. :smile:

**Comment by Nitrogen-Dioxide** [comment]
@Alexander01998 
xD

**Comment by mcccs** [comment]
lol

**Pull request merged**
