### PR TITLE
Created a .give command to get custom items in creative

### LINKED ISSUE #342: Give command for creative mode
I noticed that the .drop infinite command can drop command blocks and muchroom blocks or other blocks that cant be obtained in normal creative servers without /give. it would be cool if you can add a command like .give [id] and it will give you the item like a command block in creative mode. also in single player you can't do /give portal 1 or /give fire 1 because its 1.8 but in multiplayer servers that have spigot and are 1.7.10 and you join as 1.8 the items are glitched you can still give your self fire and portal they just have diffrent textures like the fire is the texture of flint and steel. the main reason i want this is for portal trapping

### PR DESCRIPTION
**Pull request by kim-yannick**
Closes #342

### CODE REVIEW

**Comment by kim-yannick** [comment]
Should i make templates for things that are already implemented as a mod? Like KillPotion, TrollPotion, CrashItem and others?

**Comment by mcccs** [comment]
No but we need crashsign

**Comment by kim-yannick** [comment]
CrashSign by Wolfram? I don't know how this works, but this would be not good as a template, because you also need a protection against this, which cannot be achieved by a simple item template. Maybe you can add a new issue (if it doesn't exist already).

**Comment by GlitchHead** [comment]
:D

**Comment by kim-yannick** [comment]
What's so funny?

**Comment by GlitchHead** [comment]
im not laughing im just happy that this is getting implemented i just wish this was in 2.2 :c

**Comment by kim-yannick** [comment]
Does someone have ideas for item templates?

**Comment by mcccs** [comment]
@kim-yannick https://github.com/Wurst-Imperium/Wurst-Client/issues/1525

**Comment by kim-yannick** [comment]
@mcccs There are already two similar items. One Hit Sword and Invincibility Potion.

**Comment by Huanjohn** [comment]
What about getting items using their numerical id's?

**Comment by mcccs** [comment]
I can't get an item with a space in his name

**Comment by Alexander01998** [comment]
> I can't get an item with a space in his name

It works almost exactly like the `/give` command:
`/give wooden_door`
`.give wooden_door`

**Pull request merged**
