### PR TITLE
1.9

### PR DESCRIPTION
**Pull request by nigel12341**
please update to 1.9

### CODE REVIEW

**Comment by mcccs** [comment]
@nigel12341 https://www.youtube.com/watch?v=6bpItRBFYb8

**Comment by kim-yannick** [comment]
What is this random PR? I have seen the same commits and messages in multiple PRs.

**Comment by mcccs** [comment]
They make a pul request that compares crash and Master

**Comment by kim-yannick** [comment]
Lol. So just to use it as a Issues replacement?

**Comment by mcccs** [comment]
Yes.

**Comment by arielelbaz1** [comment]
Do it plzzzzzz
i cant wait anymore!

**Comment by kim-yannick** [comment]
1.9 sucks. Also, PRs are not to ask for features. Can you please close the
conversation @Alexander01998?

**Pull request closed without merging**
