### PR TITLE
"FastRun" Mod (Only works on vanilla/Only on flat surfaces.)

### PR DESCRIPTION
**Pull request by ayylmaogitgud**
Allows a player to run very fast (much like speed) on vanilla servers by setting the player's position in **increments** (0.10 blocks per iteration cycle). Only works on flat surfaces.

GIF: https://i.gyazo.com/f63654f4850cc3ad76455d0e533e3a52.gif

Pretty neat for traveling very fast. Has "block speeds" of 1-10.

**EDIT**: Test Results:
-Vanilla: Works
-CraftBukkit (no NCP): Works
-Spigot (no NCP): Works
-CraftBukkit (NCP): SurvivalFly Detections
-Spigot (NCP): SurvivalFly Detections
-Mineplex: "Shoots" back to previous positions (I'm guessing SurvivalFly detections)

### CODE REVIEW

**Comment by ThisTestUser** [comment]
What does the IsFlat do?

**Comment by ayylmaogitgud** [comment]
Checks if the 3x3 area is flat. The hack only works when the surface is **completly** flat, or we will get invalid movement detections.

**Comment by ThisTestUser** [comment]
I don't think we need that though.
Also, do you think it would work on Mineplex?

**Comment by ayylmaogitgud** [comment]
It probably would not because of the SurvivalFly check. I would guess a (new) hack I'm making would probably work, but this, I would guess not.

**Comment by ThisTestUser** [comment]
By vanilla, would Spigot servers without anticheat plugins work?
Also, for isFlat, the user would see the hack stop before noticing that isFlat is false, so there is really not a need for it.

**Comment by ayylmaogitgud** [comment]
Yes, this works with default spigot without anticheat plugins. For the other thing, I might remove it if Alexander says too.

**Comment by Alexander01998** [comment]
Wurst already has SpeedHack and Timer. They can produce the same results with fewer restrictions.

**Comment by ThisTestUser** [comment]
But this hack is the only thing that can walk extremely fast without side effects like faster potion effects and mobs glitching.

**Pull request closed without merging**
