### PR TITLE
Make AntiPotion block ALL bad potion effects.

### PR DESCRIPTION
**Pull request by ThisTestUser**
Currently it blocks hunger and poison, it should block all bad effects.
This is my first pull request, please edit mistakes in it.

### CODE REVIEW

**Comment by liach** [comment]
Do they share the same mechanics? Not likely.

**Comment by Alexander01998** [comment]
The list of effects looks good, but the code is currently not compliant with the Java syntax.

Assuming that you haven't already, I recommend you to learn some of the Java basics before making a Pull Request here.

**Comment by ThisTestUser** [comment]
mcccs updated it, is it ok now?

**Comment by Alexander01998** [comment]
Yes, that should work.

**Comment by ThisTestUser** [comment]
So can it be merged?

**Comment by ThisTestUser** [comment]
Is there anything else to be done?

**Comment by Alexander01998** [comment]
Merged.

**Pull request closed without merging**
