### PR TITLE
This is not a session Token?

### PR DESCRIPTION
**Pull request by Tropfer**
Lately i wanted to hack again so i searched for a token id and found this: http://pastebin.com/pV2Nyau0

But why it says "This is not a session Token"
I inserted the token. And sorry, i dont understand the thing with compare and base.

### CODE REVIEW

**Comment by kim-yannick** [comment]
PULL REQUESTS ARE NOT FOR DOING ISSUES! If you guys continue abusing it,
maybe Alex will close them, which makes contributing almost impossible!
STOP DOING THAT!
Am 14.03.2016 18:38 schrieb "tropfer" <notifications@github.com>:

**Comment by mcccs** [comment]
THEN TRY OTHER WEBSITES

**Comment by ThisTestUser** [comment]
Session stealer has been patched because Mojang removed session ids from launcher logs, and that session ids cannot be shared between multiple IPs. That session is a fake,

**Comment by awakened-game** [comment]
@Tropfer you must be joking... you cant be that daft.. can you not read? 
It says "1337535510N" **of course its fake**.

**Comment by Alexander01998** [comment]
@Tropfer 

> PULL REQUESTS ARE NOT FOR DOING ISSUES! If you guys continue abusing it,
> maybe Alex will close them, which makes contributing almost impossible!
> STOP DOING THAT!

And as always, people who abuse Pull Requests like that get permanently banned from all Wurst-Imperium repositories.

**Pull request closed without merging**
