### PR TITLE
Fixed Box ESP

### PR DESCRIPTION
**Pull request by HypnoHacks**
The box esp should work fine with this code, it is what I use in Protocol for box ESP.

### CODE REVIEW

**Comment by mcccs** [comment]
Wrong repository. Please open it on [Wurst 1.9 repository](https://github.com/Wurst-Imperium/Wurst-Client-for-MC-1.9.X)

**Comment by kim-yannick** [comment]
So you are contributing to Wurst, too? That's cool. At least one guy that
is not hating other clients because they have their own.

**Comment by mcccs** [comment]
> So you are contributing to Wurst, too? That's cool. At least one guy that
is not hating other clients because they have their own.

Yes! Welcome to the world of contributing! Thank you!

**Comment by HypnoHacks** [comment]
Well of course I want to help wurst, I personally think it's a pretty cool client. Especially that new navigator menu, that is really cool.

**Pull request closed without merging**
